# Generated by Django 4.2.5 on 2023-09-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
