# Generated by Django 4.2.5 on 2023-09-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0002_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('categoria_empresa', models.CharField(max_length=200)),
                ('quitado', models.BooleanField(default=False)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.stand')),
            ],
        ),
    ]
